# conf is the parameter in whole experiments
# this also the first part of this project. 
# all options are listed in the following.

# in train.py file, we can dirctly asign a training or testing file.

# base parameters

WORK_PATH: "/home/User/xxx/resgait"   # the root path of this project
writer : 'Path_to_tensorlog'  # None
writer_name : 'config/test'
# time_span : True # For time span Exp only.
# dataset

data:    
    name: "silhouette"    # "pose", "silhouette";
    dir: "Path_TO_Downloading_dataset/silhouette"
    cache: True   # whether to use a caching strategy
    cache_path: "Path_to_save_cache_data"
    pid_num: 86 
    pid_shuffle: True
    resolution: 64
    frame_num: 28
    num_workers: 4
    drop_last: False
    collate_fn: 'clip' # options: "pose", "clip", and "select". 'pose' for pose data, 'clip' and 'select' are for image data 
    sampler: "batch"   # options: "batch" and "weight" 
    appendix: "normalization"     # 'normalization' only for silhouette of ReSGait Dataset.

model:
    name: 'SilhouetteNormal' # For model structure, please check the folder of `./model/`.

train:
    restore_iter: 0  # checkpoint
    num_epochs: 8000
    num_grad_acc: 5
    batch_size:
        batch1: 16 # Number of Subjects in one batch.
        batch2: 16 # Number of Video Sequnce in each selected subject.

test:
    evaluator: 'l2'


optimizer:
    name: 'adam'  # options: cross_entropy, softmax_center
    params:
        lr: 0.0001


scheduler:
    name: 'step' # step, multistep, exponential


loss:
    name: 'cross_entropy' # cross_entropy, softmax_center, cross_weight
    params:
        gamma: 0.0008

